name: Deploy BoogleMeet Web Application
on:
  push:
    branches:
    - main
    paths:
    - apps/booglemeet-web/**

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Build Docker Image
        run: docker build --no-cache -t salimshamim/booglemeet-web -f apps/booglemeet-web/Dockerfile .
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Publish Image to docker hub
        run: docker push salimshamim/booglemeet-web:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Image from Docker hub 
        run: docker pull salimshamim/booglemeet-web:latest
      - name: Delete old Container 
        run: docker rm -f booglemeet-web-container
      - name: Run Docker Container
        run: docker run -d -p 80:3000 --name booglemeet-web-container salimshamim/booglemeet-web:latest